version: "3"

services:
  # backend
  backend:
    build: 
      context: backend/
      dockerfile: Dockerfile
    expose: 
      - "3001"
    restart: unless-stopped

  # frontend
  frontend:
    build: 
      context: frontend/
      dockerfile: Dockerfile
    expose: 
      - "3000"
    restart: "unless-stopped"
    depends_on: 
      - backend
      - rtmp

  # rtmp
  rtmp:
    build: 
      context: rtmp/
    expose: 
      - "8000"
      - "1935"
    ports:
      - "1935:1935"
    restart: unless-stopped
    volumes: 
      - "./rtmp/nginx.conf:/etc/nginx/nginx.conf"

  # Proxy gateaway
  gateway: 
    build:
      context: reverse_proxy/
    ports: 
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes: 
      - "./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./reverse_proxy/localhost.crt:/etc/nginx/certs/localhost.crt"
      - "./reverse_proxy/localhost.key:/etc/nginx/certs/localhost.key"