version: "3"

services:
  # backend (Development)
  backend:
    build: 
      context: backend/
      dockerfile: Dockerfile.dev
    expose: 
      - "3001"
    restart: unless-stopped
    depends_on:
      - rtmp

  # frontend (Development)
  frontend:
    build: 
      context: frontend/
      dockerfile: Dockerfile.dev
    expose: 
      - "3000"
    restart: "unless-stopped"
    depends_on: 
      - backend
      - rtmp

  # rtmp (Development)
  rtmp:
    build: 
      context: rtmp/
    expose: 
      - "8000"
      - "1935"
    ports:
      - "1935:1935"
    restart: unless-stopped

  # Proxy gateaway
  gateway: 
    build:
      context: reverse_proxy/
    ports: 
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    depends_on:
      - backend
      - frontend
