name: Staging Docker Imaging - Frontend

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**

env:
  TAGS: ${{ github.sha }}
  
  # Please fill this
  DOCKER_REPOSITORY: kaenova/halliu-frontend

jobs: 
  DockerImagingService:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./frontend # Don't forget to fill this
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --tag "$DOCKER_REPOSITORY:$TAGS" .

      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Dockerhub Push
        run: docker push $DOCKER_REPOSITORY --all-tags